### ISSUE TITLE
Definição das personas

### ISSUE THREAD

**Issue by thalesmanoel** [JoaoPedro-GO/Projeto-ESII#13]
ARQUIVO PERSONAS: https://docs.google.com/document/d/19n6_tmkUlwAOwde87S4E9ORlzxiiwaUX3Wo64fDT1bU/edit?usp=sharing

**Comment by JoaoPedro-GO** [comment]
- [ ] Definir as personas que serao afetadas pelo projeto de plataforma de estudos

**Comment by glaucotodesco** [comment]
Adequar as personas a realidade do projeto
