### ISSUE TITLE
Entrega Parcial do Projeto

### ISSUE THREAD

**Issue by MiguelJDelgado** [JoaoPedro-GO/Projeto-ESII#27]

**Comment by MiguelJDelgado** [comment]
Entrega parcial do projeto, utilizando as telas de baixa fidelidade como base

**Comment by glaucotodesco** [comment]
Considera o TRI:

A correção das provas objetivas do Enem é feita por meio da Teoria de Resposta ao Item (TRI), um método estatístico que considera a dificuldade das questões respondidas corretamente. A TRI é conhecida como método antichute, pois consegue identificar se o candidato acertou uma questão por ter conhecimento ou por ter chutado.
